import { rating } from "@material-tailwind/react";
import { sub } from "date-fns";

const lugares = [
    // HOSPEDAJE
    {
        nombre: 'Cabañas El Patagón',
        lat: -45.4150,
        lng: -73.1221,
        tipo: 'hospedaje',
        descripcion: 'Cabañas en un entorno natural en la Patagonia, perfectas para desconectar.',
        precio: 80000,
        contacto: '+56 9 8765 4321',
        direccion: 'Cerro Castillo, Región de Aysén',
        categoria: 'Propiedad',
        subcategoria: 'Cabaña',
        horario_apertura: '24 horas',
        horario_cierre: '24 horas',
        imagen: 'https://www.chaletcerrocastillo.com/wp-content/uploads/2020/08/chalet-.jpg',
        rating: 4.5
    },
    {
        nombre: 'Hostal La Cabaña',
        lat: -29.5173,
        lng: -71.6684,
        tipo: 'hospedaje',
        descripcion: 'Acogedor hostal en el Valle de Elqui, ideal para quienes buscan tranquilidad.',
        precio: 40000,
        contacto: '+56 9 1234 5678',
        direccion: 'Elqui, Región de Coquimbo',
        categoria: 'Propiedad',
        subcategoria: 'Hostelería',
        horario_apertura: '24 horas',
        horario_cierre: '24 horas',
        imagen: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/35/2e/46/cosmo-elqui-valley.jpg?w=1200&h=-1&s=1',
        rating: 4.2
    },
    {
        nombre: 'Refugio de montaña Los Cóndores',
        lat: -41.0401,
        lng: -72.0761,
        tipo: 'hospedaje',
        descripcion: 'Un refugio de montaña en la Patagonia, rodeado de naturaleza.',
        precio: 15000,
        contacto: '+56 9 7654 3210',
        direccion: 'Coyhaique, Región de Aysén',
        categoria: 'Camping',
        subcategoria: 'Camping',
        horario_apertura: '24 horas',
        horario_cierre: '24 horas',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTp6cUNSEn5h0esrXV4MVwCF5WWPnFCmqtcuA&s',
        rating: 4.0
    },

    // CENTROS DEPORTIVOS
    {
        nombre: 'Centro Deportivo Valle del Elqui',
        lat: -30.0580,
        lng: -70.7314,
        tipo: 'centro',
        descripcion: 'Instalaciones deportivas para fútbol y otros deportes en un entorno rural.',
        precio: 5000,
        contacto: '+56 9 2345 6789',
        direccion: 'Valle del Elqui, Región de Coquimbo',
        categoria: 'Servicios y Oficios',
        subcategoria: 'Tiempo libre y Deporte',
        horario_apertura: '08:00 AM',
        horario_cierre: '08:00 PM',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjTW-VOWKLZrxP-o_em3DDN-PUKQLy32WtMg&s',
        rating: 5.0
    },
    {
        nombre: 'Club Deportivo Río Claro',
        lat: -35.5794,
        lng: -71.0542,
        tipo: 'centro',
        descripcion: 'Club que ofrece actividades deportivas en un ambiente familiar.',
        precio: 7000,
        contacto: '+56 9 8765 4321',
        direccion: 'Río Claro, Región del Maule',
        categoria: 'Servicios y Oficios',
        subcategoria: 'Tiempo libre y Deporte',
        horario_apertura: '09:00 AM',
        horario_cierre: '09:00 PM',
        imagen: 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        rating: 4.8
    },

    // EVENTOS
    {
        nombre: 'Fiesta del Viento',
        lat: -35.7533,
        lng: -71.7033,
        tipo: 'eventos',
        descripcion: 'Evento anual que celebra la cultura local con música y danzas.',
        precio: 0,
        contacto: '+56 9 5678 1234',
        direccion: 'Curicó, Región del Maule',
        categoria: 'Eventos',
        subcategoria: 'Eventos',
        horario_apertura: '10:00 AM',
        horario_cierre: '10:00 PM',
        imagen: 'https://www.castelloninformacion.com/wp-content/uploads/2024/01/festival-cometas.jpg',
        rating: 's/n'
    },
    {
        nombre: 'Feria Costumbrista de Las Cabras',
        lat: -34.6581,
        lng: -70.4460,
        tipo: 'eventos',
        descripcion: 'Feria que muestra tradiciones y productos locales de la zona.',
        precio: 0,
        contacto: '+56 9 2345 6789',
        direccion: 'Las Cabras, Región de O\'Higgins',
        categoria: 'Eventos',
        subcategoria: 'Eventos',
        horario_apertura: '09:00 AM',
        horario_cierre: '05:00 PM',
        imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLvV61De4OClkKAKRsigpqN1L1se-qG6IagQ&s',
        rating: 4.6
    },

    // GASTRONOMIA
    {
        nombre: 'Restaurante Casa de Campo',
        lat: -34.1204,
        lng: -70.8196,
        tipo: 'gastronomia',
        descripcion: 'Un restaurante rural que ofrece platos tradicionales chilenos.',
        precio: 12000,
        contacto: '+56 9 4567 8901',
        direccion: 'Rancagua, Región de O\'Higgins',
        categoria: 'Servicios y Oficios',
        subcategoria: 'Restaurantes y Comida',
        horario_apertura: '12:00 PM',
        horario_cierre: '10:00 PM',
        imagen: 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        rating: 4.3
    },
    {
        nombre: 'Comida Típica del Sur',
        lat: -39.6286,
        lng: -73.1557,
        tipo: 'gastronomia',
        descripcion: 'Restaurante familiar que ofrece comida casera típica del sur de Chile.',
        precio: 10000,
        contacto: '+56 9 8765 4321',
        direccion: 'Temuco, Región de La Araucanía',
        categoria: 'Servicios y Oficios',
        subcategoria: 'Restaurantes y Comida',
        horario_apertura: '10:00 AM',
        horario_cierre: '08:00 PM',
        imagen: 'https://ralfvanveen.com/wp-content/uploads/2021/06/Placeholder-_-Glossary.svg',
        rating: 4.7
    },

    // SERVICIOS COMUNITARIOS
    {
        nombre: 'Centro Comunitario de Coyhaique',
        lat: -45.5712,
        lng: -72.0655,
        tipo: 'servicio',
        descripcion: 'Un centro que ofrece apoyo a la comunidad con diversas actividades.',
        precio: 'Entrada gratuita',
        contacto: '+56 9 8765 4321',
        direccion: 'Coyhaique, Región de Aysén',
        categoria: 'Servicios Comunitarios',
        horario_apertura: '09:00 AM',
        horario_cierre: '05:00 PM'
    },
    {
        nombre: 'Junta de Vecinos San Vicente',
        lat: -33.6902,
        lng: -70.7806,
        tipo: 'servicio',
        descripcion: 'Organización que promueve actividades para la comunidad local.',
        precio: 'Entrada gratuita',
        contacto: '+56 9 2345 6789',
        direccion: 'San Vicente, Región del Libertador General Bernardo O\'Higgins',
        categoria: 'Servicios Comunitarios',
        horario_apertura: '09:00 AM',
        horario_cierre: '06:00 PM'
    },

    // OFICIOS
    {
        nombre: 'Carpintería La Madera',
        lat: -36.7276,
        lng: -72.0521,
        tipo: 'oficios',
        descripcion: 'Carpintería local que ofrece productos de madera hechos a mano.',
        precio: 'Varía según el producto',
        contacto: '+56 9 7894 5632',
        direccion: 'Talcahuano, Región del Biobío',
        categoria: 'Oficios',
        horario_apertura: '08:00 AM',
        horario_cierre: '06:00 PM'
    },
    {
        nombre: 'Maestro Chasquilla El Alto',
        lat: -33.6143,
        lng: -70.4552,
        tipo: 'oficios',
        descripcion: 'Servicio de maestro chasquilla en la localidad de El Alto.',
        precio: 'Desde $15,000 CLP',
        contacto: '+56 9 1234 5678',
        direccion: 'El Alto, Región Metropolitana',
        categoria: 'Oficios',
        horario_apertura: '08:00 AM',
        horario_cierre: '06:00 PM'
    },

    // TURISMO
    {
        nombre: 'Parque Nacional Altos de Lircay',
        lat: -35.7240,
        lng: -71.3924,
        tipo: 'turismo',
        descripcion: 'Un parque nacional que ofrece rutas de senderismo y una rica biodiversidad.',
        precio: 0,
        contacto: '+56 9 5678 9012',
        direccion: 'Parque Nacional Altos de Lircay, Región del Maule',
        categoria: 'Servicios y Oficios',
        subcategoria: 'Tours y Transporte',
        horario_apertura: '08:00 AM',
        horario_cierre: '06:00 PM',
        imagen: 'https://www.diarioelcentro.cl/wp-content/uploads/2022/12/Altos-de-Lircay-2.jpg',
        rating: 4.9
    },
    {
        nombre: 'Salto del Laja',
        lat: -37.2244,
        lng: -71.3010,
        tipo: 'turismo',
        descripcion: 'Una hermosa cascada ubicada en la Región del Biobío, ideal para un picnic.',
        precio: 'Entrada libre',
        contacto: 'No disponible',
        direccion: 'Salto del Laja, Región del Biobío',
        categoria: 'Turismo',
        horario_apertura: '24 horas',
        horario_cierre: '24 horas'
    },
    {
        nombre: 'Laguna del Laja',
        lat: -37.7111,
        lng: -71.5293,
        tipo: 'turismo',
        descripcion: 'Un hermoso lugar para disfrutar de la naturaleza y realizar deportes acuáticos.',
        precio: 'Entrada: $2,500 CLP',
        contacto: '+56 42 241 7117',
        direccion: 'Laguna del Laja, Región del Biobío',
        categoria: 'Turismo',
        horario_apertura: '08:00 AM',
        horario_cierre: '06:00 PM'
    },
    {
        nombre: 'Termas de Chillán',
        lat: -36.8532,
        lng: -71.4482,
        tipo: 'turismo',
        descripcion: 'Termas naturales en la región de Ñuble, perfectas para relajarse.',
        precio: 20000,
        contacto: '+56 42 241 7117',
        direccion: 'Termas de Chillán, Región de Ñuble',
        categoria: 'Servicios y Oficios',
        subcategoria: 'Mundo Familiar y Salud',
        horario_apertura: '09:00 AM',
        horario_cierre: '09:00 PM',
        imagen: 'https://termaschillan.cl/wp-content/uploads/2022/10/puerto_htch_jun2019-514-Edit-1024x683.jpg',
        rating: 5
    },
    {
        nombre: 'Cerro San Pedro',
        lat: -40.2500,
        lng: -73.0833,
        tipo: 'turismo',
        descripcion: 'Una montaña poco conocida, ideal para el senderismo y la exploración.',
        precio: 'Entrada gratuita',
        contacto: 'No disponible',
        direccion: 'Región de Los Lagos',
        categoria: 'Turismo',
        horario_apertura: '24 horas',
        horario_cierre: '24 horas'
    },
    {
        nombre: 'Aldea Los Ríos',
        lat: -39.7330,
        lng: -73.1260,
        tipo: 'turismo',
        descripcion: 'Una aldea rural con paisajes hermosos y una rica cultura local.',
        precio: 'Entrada gratuita',
        contacto: 'No disponible',
        direccion: 'Aldea Los Ríos, Región de Los Ríos',
        categoria: 'Turismo',
        horario_apertura: '24 horas',
        horario_cierre: '24 horas'
    },
    {
        nombre: 'Río Yelcho',
        lat: -43.4281,
        lng: -72.9292,
        tipo: 'turismo',
        descripcion: 'Un hermoso río en la Patagonia, ideal para la pesca y el kayak.',
        precio: 0,
        contacto: 'No disponible',
        direccion: 'Río Yelcho, Región de Los Lagos',
        categoria: 'Servicios y Oficios',
        subcategoria: 'Tours y Transporte',
        horario_apertura: '24 horas',
        horario_cierre: '24 horas',
        imagen :'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRW7MxUQCL7EPugV5e4d23OE0IbIK6aC3z1TA&s',
        rating: 5
    }
];

export default lugares;